export const errorMessage = {
  not_found: "Resource not found",
  bad_request: "Bad request",
  unauthorized: "Unauthorized",
  forbidden: "Forbidden",
  conflict: "Resource already exists",
  internal_server_error: "Internal server error",
  invalid_input: "Invalid input",
  method_not_allowed: "Method not allowed",
  too_many_requests: "Too many requests",
  post_not_found: "Post not found",
  category_not_found: "Category not found",
  post_category_not_found: "Post category not found",
  post_category_already_exists: "Post category already exists",
  unprocessable_entity: "Unprocessable entity",
  post_already_exists: "Post already exists",
  category_already_exists: "Category already exists",
  posts_retrieved_successfully: "Posts retrieved successfully",
  post_retrieved_successfully: "Post retrieved successfully",
  category_retrieved_successfully: "Category retrieved successfully",
  posts_created_successfully: "Posts created successfully",
  post_created_successfully: "Post created successfully",
  posts_updated_successfully: "Posts updated successfully",
  post_updated_successfully: "Post updated successfully",
  posts_deleted_successfully: "Posts deleted successfully",
  post_deleted_successfully: "Post deleted successfully",
  categories_retrieved_successfully: "Categories retrieved successfully",
  categories_created_successfully: "Categories created successfully",
  category_created_successfully: "Category created successfully",
  categories_updated_successfully: "Categories updated successfully",
  category_updated_successfully: "Category updated successfully",
  categories_deleted_successfully: "Categories deleted successfully",
  category_deleted_successfully: "Category deleted successfully",
};
